[package]
name = "shapes"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.19.3"
ply-rs = "0.1.3"
image = "0.23.14"
obj-rs = "0.6.3"
